
package cn.kuifir.moduel.generatedCode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceTestImpl", targetNamespace = "http://impl.service.moduel.kuifir.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceTestImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "weather", targetNamespace = "http://impl.service.moduel.kuifir.cn/", className = "cn.kuifir.moduel.generatedCode.Weather")
    @ResponseWrapper(localName = "weatherResponse", targetNamespace = "http://impl.service.moduel.kuifir.cn/", className = "cn.kuifir.moduel.generatedCode.WeatherResponse")
    @Action(input = "http://impl.service.moduel.kuifir.cn/ServiceTestImpl/weatherRequest", output = "http://impl.service.moduel.kuifir.cn/ServiceTestImpl/weatherResponse")
    public String weather(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "people", targetNamespace = "http://impl.service.moduel.kuifir.cn/", className = "cn.kuifir.moduel.generatedCode.People")
    @ResponseWrapper(localName = "peopleResponse", targetNamespace = "http://impl.service.moduel.kuifir.cn/", className = "cn.kuifir.moduel.generatedCode.PeopleResponse")
    @Action(input = "http://impl.service.moduel.kuifir.cn/ServiceTestImpl/peopleRequest", output = "http://impl.service.moduel.kuifir.cn/ServiceTestImpl/peopleResponse")
    public String people(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
