package cn.kuifir.module.generatedCode;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-06T11:13:20.753+08:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "CommonAPI",
                  wsdlLocation = "http://mdev.cnooc.com.cn/mp/api/common?wsdl",
                  targetNamespace = "http://mobile.cnooc.com.cn/api/common")
public class CommonAPI extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mobile.cnooc.com.cn/api/common", "CommonAPI");
    public final static QName CommonAPIPort = new QName("http://mobile.cnooc.com.cn/api/common", "CommonAPIPort");
    static {
        URL url = null;
        try {
            url = new URL("http://mdev.cnooc.com.cn/mp/api/common?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommonAPI.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://mdev.cnooc.com.cn/mp/api/common?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CommonAPI(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommonAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonAPI() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CommonAPI(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CommonAPI(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CommonAPI(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ICommonAPI
     */
    @WebEndpoint(name = "CommonAPIPort")
    public ICommonAPI getCommonAPIPort() {
        return super.getPort(CommonAPIPort, ICommonAPI.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICommonAPI
     */
    @WebEndpoint(name = "CommonAPIPort")
    public ICommonAPI getCommonAPIPort(WebServiceFeature... features) {
        return super.getPort(CommonAPIPort, ICommonAPI.class, features);
    }

}
