package aaa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-21T14:50:28.427+08:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "http://impl.service.moduel.kuifir.cn/", name = "ServiceTestImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceTestImpl {

    @WebMethod
    @Action(input = "http://impl.service.moduel.kuifir.cn/ServiceTestImpl/peopleRequest", output = "http://impl.service.moduel.kuifir.cn/ServiceTestImpl/peopleResponse")
    @RequestWrapper(localName = "people", targetNamespace = "http://impl.service.moduel.kuifir.cn/", className = "aaa.People")
    @ResponseWrapper(localName = "peopleResponse", targetNamespace = "http://impl.service.moduel.kuifir.cn/", className = "aaa.PeopleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String people(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @Action(input = "http://impl.service.moduel.kuifir.cn/ServiceTestImpl/weatherRequest", output = "http://impl.service.moduel.kuifir.cn/ServiceTestImpl/weatherResponse")
    @RequestWrapper(localName = "weather", targetNamespace = "http://impl.service.moduel.kuifir.cn/", className = "aaa.Weather")
    @ResponseWrapper(localName = "weatherResponse", targetNamespace = "http://impl.service.moduel.kuifir.cn/", className = "aaa.WeatherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String weather(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
