
package bbb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceTestImplService", targetNamespace = "http://impl.service.moduel.kuifir.cn/", wsdlLocation = "http://localhost:9999/service?wsdl")
public class ServiceTestImplService
    extends Service
{

    private final static URL SERVICETESTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICETESTIMPLSERVICE_EXCEPTION;
    private final static QName SERVICETESTIMPLSERVICE_QNAME = new QName("http://impl.service.moduel.kuifir.cn/", "ServiceTestImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICETESTIMPLSERVICE_WSDL_LOCATION = url;
        SERVICETESTIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceTestImplService() {
        super(__getWsdlLocation(), SERVICETESTIMPLSERVICE_QNAME);
    }

    public ServiceTestImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICETESTIMPLSERVICE_QNAME, features);
    }

    public ServiceTestImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICETESTIMPLSERVICE_QNAME);
    }

    public ServiceTestImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICETESTIMPLSERVICE_QNAME, features);
    }

    public ServiceTestImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceTestImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceTestImpl
     */
    @WebEndpoint(name = "ServiceTestImplPort")
    public ServiceTestImpl getServiceTestImplPort() {
        return super.getPort(new QName("http://impl.service.moduel.kuifir.cn/", "ServiceTestImplPort"), ServiceTestImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceTestImpl
     */
    @WebEndpoint(name = "ServiceTestImplPort")
    public ServiceTestImpl getServiceTestImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.moduel.kuifir.cn/", "ServiceTestImplPort"), ServiceTestImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICETESTIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICETESTIMPLSERVICE_EXCEPTION;
        }
        return SERVICETESTIMPLSERVICE_WSDL_LOCATION;
    }

}
